from durable.lang import *

with ruleset('jaka_gra_planszowa'):
    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'nie') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def GaldorsGrip(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Galdor's Grip", 'opis': "Galdor's Grip to jednoosobowa gra karciana osadzona w świecie fantasy, którą można rozgrywać całkowicie w dłoniach. Gracz przegląda talię, wykorzystując akcje i zdolności kart, aby strategicznie manipulować ich kolejnością i orientacją. Celem jest osiągnięcie wymaganej liczby punktów poprzez realizację celów, unikając jednocześnie sytuacji prowadzących do porażki" })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'nie') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def AwakenTheAncients(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Awaken the Ancients", 'opis': "W grze Awaken the Ancients starannie zarządzaj ograniczonym zapasem żetonów nasion, aby wykonać unikalne rytuały przebudzenia dostosowane do każdego Pradawnego. Będziesz strategicznie przesuwać nasiona w stylu Mancala po siatce 8 starożytnych, umieszczając je na określonych starożytnych, aby spełnić ich wymagania dotyczące przebudzenia. Gdy Pradawny zostanie przebudzony, może skonsumować pewne nasiona, aby się pożywić, usuwając je z gry. Wyzwanie polega na planowaniu swoich ruchów, aby upewnić się, że wszystkich ośmiu Pradawnych zostanie przebudzonych, zanim skończą się nasiona lub ukończenie rytuałów stanie się niemożliwe. Mądrze zarządzaj swoimi zasobami i wykorzystuj zdolności Strażników, aby kontrolować kierunek ruchu nasion, dążąc do zwycięstwa poprzez przebudzenie wszystkich Pradawnych. Po zwycięstwie końcowy wynik jest równy liczbie nasion pozostałych w grze. " })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'nie') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def OldTownRoad(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Old Town Road" ,'opis': "Old Town Road to solowa gra karciana, w której gracze spotykają się z banitami na niesławnej drodze prowadzącej do Starego Miasta. W swojej turze użyjesz akcji na jednej z 6 zakrytych kart, strzelając do celów lub rabując banki, aby odwrócić karty w celu zwiększenia PZ lub odłożyć karty na tył talii, tworząc sekwencje 3-kartowych układów pokerowych, wartych PZ na koniec gry. Na koniec gry gracz oblicza swój wynik, sumując punkty za każdą z sekwencji pokerowych, a także PZ za poszukiwane plakaty i napady na banki. Gra składa się z 24 kart postaci, 4 kart lokali i karty referencyjnej Starego Miasta." })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'nie') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def Rails(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "30Rails", 'opis': "Ołówkowo-papierowa gra w budowanie sieci kolejowych dla jednego lub więcej graczy. 30 Rails rozgrywa się na siatce 6 x 6 kwadratów. Najpierw każdy gracz rysuje na swoim arkuszu góry, kopalnię i cztery stacje. Następnie gra składa się z trzydziestu tur, które wypełnią pozostałą część siatki torami. W każdej turze rzucane są dwie kości. Jedna kość określa, który typ toru zostanie umieszczony, a druga określa ograniczenia co do tego, gdzie tor może zostać umieszczony. Zwycięzcą zostaje gracz, który połączy najwięcej stacji ze sobą i z kopalnią." })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'nie') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def GloomHoldin(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "GloomHoldin", 'opis': "Gloomholdin' to 18-kartowa, niewymagająca stołu wersja Gloomhaven. Można go zagrać w całości z ręki, ale zapewniam też sposób na zagranie go na stole." })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'nie') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def RollCrawl(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Roll Crawl", 'opis': "Kraina jest w niebezpieczeństwie! Dwóch dzielnych bohaterów, wraz ze swoim wiernym towarzyszem, musi zmierzyć się z wrogami o rosnącym poziomie trudności, a także z wymagającym finałowym bossem, wykorzystując jedynie swój spryt i umiejętności. Każdy gracz rzuca 3 kośćmi dla swojej postaci, wykorzystując mechanikę push-your-luck, aby spróbować aktywować swoje najpotężniejsze umiejętności lub zadowolić się wszelkimi obrażeniami, jakie mogą uzyskać, w zależności od ich strategii. Roll Crawl to gra dla 1 do 2 graczy, w której dwóch bohaterów próbuje aktywować własne zdolności, aby zredukować zdrowie przeciwników do zera. Mogą oni zrezygnować z aktywacji własnych zdolności i połączyć swoje kości, aby aktywować zdolności swojego towarzysza. Ale cokolwiek robisz, zadawaj jak najwięcej obrażeń. Przeciwnicy są gotowi do ataku, mając więcej kości niż ty. Im więcej mają zdrowia, tym więcej kości rzucają, więc gracze muszą strategicznie decydować, kiedy jest odpowiedni moment, aby wykorzystać swoje szczęście." })
    
    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'tak') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def PalmIsland(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Palm Island", 'opis': "Palm Island to przenośna gra, którą można zabrać ze sobą wszędzie. Siedząc, stojąc, czekając, jeżdżąc, latając, relaksując się, samotnie lub razem, możesz grać w Palm Island bez stołu. Korzystając z mechaniki przekształcania talii, gracz używa tylko 17 kart w ciągu 8 rund, aby ukształtować swoją wyspę i pokonać jej unikalne wyzwania. Przechowuj zasoby, aby płacić za ulepszenia i ulepszaj budynki, aby uzyskać dostęp do nowych umiejętności. Każda podjęta decyzja zmienia wioskę z rundy na rundę. Na koniec 8 rund podlicz punkty zwycięstwa. GRAJ SAMOTNIE, zdobywając osiągnięcia i odblokowując nowe zdolności, które pomogą twojej wiosce osiągnąć jeszcze wyższy poziom. GRAJ WSPÓŁPRACUJĄC, pracując razem, aby skutecznie przygotować swoją wioskę przed klęskami żywiołowymi. GRAJ KONKURENCYJNIE, ścigając się, aby kupić bonusy, lub w trybie swobodnym, spełniając określone kryteria przed przeciwnikiem. Dodaj mieszkańców wioski do dowolnego trybu gry, których możesz rekrutować do swojej wioski i wykorzystaj ich umiejętności, aby zdobyć więcej punktów niż przeciwnik. Gra zawiera talie dla 2 graczy, karty rywalizacji, karty współpracy i karty wyczynów solowych. Wiele gier można łączyć, aby dodać jeszcze więcej graczy." })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'tak') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def DragonDungeon(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Dragon Dungeon", 'opis': "Dragon Dungeon to gra typu roll & write, w którą można grać w kółko i krzyżyk, drukując wszystkie potrzebne arkusze, aby grać samemu lub przeciwko najbardziej żądnym przygód przyjaciołom! Gracze będą rzucać kośćmi, próbując uciec z lochu, domu najzacieklejszych wrogów i straszliwego władcy smoków. Ich celem jest dotarcie do wyjścia z jaskini przed innymi graczami lub zabicie smoczego lorda podczas plądrowania i zabijania jak największej liczby wrogów. Czy masz to, czego potrzeba, aby przetrwać tę ekscytującą przygodę? A może zginiesz w ciemnym lochu, by służyć jako pożywienie dla jego diabłów? Przekonajmy się." })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'tak') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def ForNorthwood(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "For Northwood" ,'opis': "Dla Northwood! to solowa gra polegająca na zarządzaniu ręką i precyzyjnym wykonywaniu sztuczek. Twoim celem jest pokojowe zjednoczenie królestwa Northwood poprzez rozmowy z jego władcami. W ciągu ośmiu rund musisz odwiedzić osiem zwierzęcych lenn i zaangażować ich władców w dialog (triki). Kolor każdego władcy reprezentuje atut danego lenna. Każdy władca wymaga również wygrania dokładnej liczby lew, aby dołączyć do sojuszu, więc gra staje się coraz trudniejsza w miarę kurczenia się opcji. Zaczynasz z czterema sojusznikami, z których każdy ma zdolność, której możesz użyć raz na wizytę. Zdolności te mogą sprawić, że będziesz dobierać, odrzucać lub w inny sposób manipulować ręką, aby pomóc ci osiągnąć docelowy wynik. Po zdobyciu władcy możesz go tymczasowo zastąpić jednym ze swoich sojuszników, jeśli potrzebujesz bardziej szczegółowego zestawu umiejętności, aby poradzić sobie z trudniejszymi lennami. Z wieloma poziomami trudności, 24 władcami (12 używanych na grę) i broszurą z 16 scenariuszami wyzwań, For Northwood! oferuje godziny rozgrywki z nową łamigłówką za każdym razem! " })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'tak') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def DungeonPages(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Dungeon Pages", 'opis': "Dungeon Pages to taktyczna gra typu roll-and-write, w której wcielasz się w postać wyruszającą na epicką wyprawę przez różne lochy. Każdy arkusz zadania zawiera sekcję postaci i sekcję lochów. Każda sekcja przedstawia postać i jej umiejętności, a także śledzi jej zdrowie i postępy. Każda sekcja lochu przedstawia cztery pomniejsze lochy i jeden loch bossa oraz opisuje potwory i pułapki, które można w nich znaleźć. Każdy loch reprezentuje jeden z etapów misji. Przemierzając lochy w poszukiwaniu skrzyni ze skarbem, będziesz zaznaczać białe pola (puste miejsca i miejsca z pułapkami), aby reprezentować obszary, które zbadałeś. Im dokładniej zbadasz każdy loch i im więcej potworów pokonasz po drodze, tym więcej doświadczenia zdobędziesz. Wybierz kartę zadania, aby wyruszyć w podróż" })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'tak') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def DungeonOfD(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Dungeon of D", 'opis': "DARMOWA gra karciana dla JEDNEGO gracza, polegająca na przemierzaniu lochów Bez księgowości, bez kości, tylko ty, karty, żeton i loch do odkrycia! Wydostań się z lochu żywy i jak najbogatszy i jeśli jesteś w stanie, przynieś Amulet D'eugora!!!" })

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'darmowe') & (m.przesten == 'tak') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def Habits(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Habits", 'opis': "Habits to wciągająca gra w 9-kartowego pasjansa, która rzuca wyzwanie kultywowaniu dyscypliny i znaczenia w życiu.Każda karta zawiera dobry nawyk po jednej stronie i zły nawyk po drugiej, tworz¹c dynamiczne interakcje i strategiczne decyzje. Twoim celem jest obrócenie wszystkich kart na stronę dobrego nawyku, pozostawiając zły nawyk bezsilnym. Ostrożnie uruchamiaj pozytywne nawyki, aby przekształcić sąsiednie negatywne, przestawiaj karty, aby uzyskaæ maksymalne przyszłe korzyżyści lub chroñ kluczowe nawyki przed przejęciem na ciemną stronę. Poświęcaj swój czas i wysiłek mądrze, ponieważ złe nawyki pozostawione bez kontroli mogą szybko zniweczyćtwoje postępy. Opracuj skuteczną strategię, aby osiągnąą harmonijnę i równowagę dobrych nawyków i wygrać grę." })
    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'tak') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def Gates(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Gates", 'opis':"Gate to gra typu tower-defense, w której wcielasz się w rolę przywódcy małego średniowiecznego miasteczka oblężonego przez rój nikczemnych stworzeń z lokalnego lasu. Będziesz musiał zarządzać zdrowiem bramy miasta, wieży i lokalnej farmy. Ponadto atak ten powoduje wzrost poziomu strachu. Jeśli nie będziesz w stanie utrzymać bramy lub jeśli strach twoich ludzi stanie się zbyt wysoki, przegrasz grę. Jeśli jednak uda ci się powstrzymać rój wrogów wystarczająco długo, zwyciężysz! Gate wykorzystuje budowanie talii jako mechanikę napędzającą grę. Zaczynasz z trzema początkowymi kartami, ale w miarę postępów w grze będziesz mógł rekrutować nowych ludzi ze swojego miasta, aby pomóc swojej sprawie. Każda postać ma unikalne zdolności, a niektóre nawet specjalne moce. Wrogowie w grze stają się coraz trudniejsi z każdą nową falą, więc będziesz musiał dokonywać dobrych wyborów, kiedy wydawać zasoby na walkę z wrogami, ulepszanie dowództwa i naprawianie miasta."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'tak') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def CubesOfEurope(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Cubes of Europe", 'opis':"Jako europejski szlachcic z niewielką ilością ziemi masz wielkie marzenia o zostaniu europejskim szlachcicem ze znacznie większą ilością ziemi. Sprytnie używaj kości do zdobywania i umieszczania unikalnych kostek, manipuluj stanem gry za pomocą ich efektów specjalnych i zdobądź jak najwięcej punktów do końca gry."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'tak') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def GemGetterGalactic(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Gem Getter Galactic", 'opis':"W Gem Getter Galactic ty i twoi znajomi prowadzicie konkurujące ze sobą kopalnie asteroid. Odkryj bogactwa głębokiego kosmosu i zrównoważ unikalne warunki punktacji każdego klejnotu, aby stać się najlepszym zbieraczem klejnotów w galaktyce!"})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'tak') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def TranscribeTheArtOfAlchemy(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Transcribe The Art Of Alchemy", 'opis':"W Transcribe gracze wcielają się w alchemików studiujących sztukę transmutacji i opanowujących procesy alchemiczne, aby ukończyć swoje Magnum Opus i stać się najbardziej znanym alchemikiem w historii. W każdej turze gracze jednocześnie aktywują swój Silnik Transmutacji, sporządzają Mapę Astrologii, ulepszają swój Silnik i chwalą się swoimi odkryciami. Gdy gracz ukończy swoje Magnum Opus, gra wchodzi w ostatnią turę. Gracz z największą liczbą Renown (punktów zwycięstwa) na koniec gry wygrywa."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'tak') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def Deck52SpaceWrecked(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Deck 52 Space Wrecked", 'opis':"Deck 52: Space Wrecked to szybka solowa gra karciana typu dungeon crawl, w której gracz walczy na losowo generowanych poziomach opuszczonego statku kosmicznego, starając się przetrwać i dotrzeć do promu ewakuacyjnego."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'tak') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def DragonsOfEtchinstone(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Dragon's of Etchinstone", 'opis':"W grze Dragons of Etchinstone dzielny mag eteru musi pokonać cztery regiony i zmierzyć się z jednym z czterech smoków. Będziesz używać swoich kart akcji do zarządzania niebezpiecznymi podróżami i potężnymi wrogami. Pokonaj ich, a otrzymasz PD, które możesz wykorzystać do ulepszenia swoich kart akcji. Porażki lub niewielkie zwycięstwa nad podróżami skutkują utratą czasu, co może zmusić cię do stawienia czoła smokowi, zanim poczujesz się gotowy. Porażki lub niewielkie zwycięstwa nad wrogami skutkują otrzymywaniem obrażeń, co zmusza cię do obniżenia poziomu kart akcji i osłabia twoją moc."})


    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'nie') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def ImperiumClassics(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Imperium Classics", 'opis':"Przeciwko tobie stoją potężni przeciwnicy. Twoi ludzie są gotowi. Historia wzywa. W twoich rękach spoczywa przeznaczenie jednej z największych cywilizacji w historii. Pod ciągłym zagrożeniem atakiem musisz podbić nowe ziemie, nadzorować dramatyczne postępy naukowe i kulturowe oraz poprowadzić swój lud do ery imperium. Rozwijaj się zbyt szybko, a niepokoje rzucą twoją cywilizację na kolana; buduj jednak zbyt wolno, a możesz stać się zwykłym przypisem do historii. Jako jedna z ośmiu radykalnie asymetrycznych cywilizacji będziesz rywalizować o miano najbardziej dominującego imperium, jakie kiedykolwiek widział świat."})


    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'nie') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def GaiaProject(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Gaia Project", 'opis':"Gaia Project to nowa gra z serii Terra Mystica. Podobnie jak w oryginalnej Terra Mystica, czternaście różnych frakcji żyje na siedmiu różnych rodzajach planet, a frakcje są przywiązane do własnych planet macierzystych, więc aby się rozwijać i rosnąć, muszą terraformować sąsiednie planety do swoich środowisk domowych, konkurując z innymi grupami. Ponadto planety Gaia mogą być wykorzystywane przez wszystkie frakcje do kolonizacji, a planety Transdimensional mogą być zmieniane w planety Gaia. Wszystkie frakcje mogą doskonalić swoje umiejętności w sześciu różnych obszarach rozwoju: Terraformacja, Nawigacja, Sztuczna Inteligencja, Gaiaformacja, Ekonomia, Badania; prowadzące do zaawansowanej technologii i specjalnych premii. Aby to wszystko osiągnąć, każda grupa posiada specjalne umiejętności i zdolności. Obszar gry składa się z dziesięciu sektorów, co pozwala na zmienną konfigurację, a tym samym jeszcze większą wartość powtórki niż jej poprzedniczka Terra Mystica. Rozgrywka dla dwóch graczy toczy się w siedmiu sektorach."})
    
    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'nie') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def BulletHeart(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Bullet Heart", 'opis':"W Bullet Heart gracze wcielają się w bohaterki z odległej Ziemi przyszłości i wykorzystują swoje niesamowite moce, aby bronić Ziemi przed złem - a także przed sobą nawzajem! Moce każdej bohaterki manifestują się w innej formie, a gracze kontrolują dźwięk, papier, technologię, grawitację, trójkąty i nie tylko! Tury odbywają się jednocześnie. Umieszczaj pociski w polu widzenia, przy czym kolor pocisku określa kolumnę, a numer - jak daleko w tej kolumnie jest umieszczony. Użyj akcji, aby manipulować kulami, tworząc konfiguracje pasujące do twoich wzorów. Użycie wzoru usuwa kule z celownika i wysyła je do przeciwnika. Umieszczając pociski, pomijasz istniejące pociski w kolumnie, w której je umieszczasz, a pocisk trafia w ciebie, jeśli zostanie umieszczony poza zasięgiem twojego wzroku. Pod koniec tury zdobędziesz jeszcze więcej pocisków ze środkowej torby, a także to, co wysłał przeciwnik, dzięki czemu każda nowa tura będzie bardziej gorączkowa niż poprzednia!"})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'nie') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def Cartographers(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Cartographers", 'opis':"W Cartographers: A Roll Player Tale, gracze rywalizują o zdobycie największej liczby gwiazdek reputacji przed upływem czterech sezonów. Każdego sezonu gracze rysują na swoich arkuszach mapy i zdobywają reputację, wykonując edykty królowej przed zakończeniem sezonu. Gracz z największą liczbą gwiazdek reputacji na koniec zimy wygrywa!"})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'nie') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def MachinaArcana(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Machina Arcana", 'opis':"W Machina Arcana gracze wcielają się w rolę odkrywców, którzy badają starożytny podziemny kompleks nieznanego pochodzenia. Zmierzą się z potworami inspirowanymi mitem Cthulhu H. P. Lovecrafta w steampunkowej scenerii. Poszukiwacze przygód zbierają sprzęt, wchodzą w interakcje z otoczeniem i wykorzystują je, walczą z potworami i zanurzają się w bogatej narracji. Cała historia jest podzielona na różne scenariusze, które stanowią samodzielną grę. Wszystkie te scenariusze zawierają rozdziały, z których każdy ma własną narrację i specyfikę. Celem gry jest postęp w opowieści i stawienie czoła grze końcowej w finale każdego scenariusza."})
 
    @when_all((m.liczba_graczy == '1') & (m.koszt1 == '<500') & (m.samodzielny_druk == 'nie') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def AeonsEnd(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Aeon's End", 'opis':"Aeon's End to gra kooperacyjna, która eksploruje gatunek deckbuilding z wieloma innowacyjnymi mechanizmami, w tym systemem zmiennej kolejności tur, który symuluje chaos ataku, oraz zasadami zarządzania talią, które wymagają starannego planowania z każdą odrzuconą kartą. Gracze będą walczyć o obronę Gravehold przed Bezimiennymi i ich hordami, wykorzystując unikalne zdolności, potężne zaklęcia i, co najważniejsze, swój wspólny spryt."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def Dominion(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Dominion", 'opis':"W Dominion każdy gracz zaczyna z identyczną, bardzo małą talią kart. Na środku stołu znajduje się wybór innych kart, które gracze mogą kupić, jeśli ich na to stać. Poprzez wybór kart do kupienia i sposób, w jaki rozgrywają swoje ręce, gdy je dobierają, gracze konstruują swoją talię na bieżąco, dążąc do najbardziej efektywnej ścieżki do cennych punktów zwycięstwa do końca gry. Dominion nie jest kolekcjonerską grą karcianą (CCG), ale rozgrywka jest podobna do budowania i rozgrywania talii CCG. Gra zawiera 500 kart. Gracz wybiera 10 z 25 typów kart królestwa, które chce wykorzystać w danej rozgrywce, co zapewnia ogromną różnorodność."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol =='tak') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def Nucleum(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Nucleum", 'opis':"Nucleum to ciężka gra planszowa euro, w której gracze wcielają się w rolę przemysłowców próbujących odnieść sukces podczas boomu gospodarczego i technologicznego w XIX-wiecznej Saksonii, napędzanego wynalezieniem i rozpowszechnieniem Nucleum (reaktora jądrowego). Gracze zdobywają punkty zwycięstwa, rozwijając swoje sieci, budując i zasilając budynki miejskie, zabezpieczając kontrakty i osiągając kamienie milowe (losowe cele końcowe). Każdy gracz otrzymuje również unikalne technologie asymetryczne, które po odblokowaniu dają mu specjalne moce. Rozgrywka jest ciągła; gracze zmieniają się jeden po drugim, bez rund ani faz."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def ProjectL(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Project L", 'opis':"Project L to szybka, dopasowująca płytki łamigłówka z trójwarstwowymi łamigłówkami 3D i pięknymi akrylowymi elementami. Rzuć wyzwanie znajomym w grze o prostej konstrukcji, ale skomplikowanej rozgrywce, która robi niezatarte wrażenie! Rdzeń gry polega na używaniu elementów do układania puzzli. Zaczynając od zaledwie dwóch podstawowych elementów, używasz trzech akcji w każdej turze, aby rozwinąć potężny silnik. Mając więcej elementów różnego typu, możesz skutecznie rozwiązywać nawet najtrudniejsze łamigłówki. Ukończone łamigłówki przyznają ci punkty lub nowe elementy, które jeszcze bardziej napędzają twój silnik. Czy uda ci się przechytrzyć przeciwników?"})
 
    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol =='tak') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def TwilightInscription(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Twilight Inscription", 'opis':"Imperium Lazax spłonęło na popiół, odrzucone przez swoich poddanych. Skutkiem tego była tragedia i drobny konflikt w równej mierze, czas strat i wyczerpania. W następujących po tym Mrocznych Latach frakcje galaktyki wycofały się i odzyskały siły. Teraz patrzą na gwiazdy i widzą okazję – szansę na odzyskanie tego, co zostało utracone. Szansę na ponowne zdefiniowanie galaktycznej cywilizacji. Szansę na pozostawienie swojego śladu na gwiazdach. Twilight Inscription, epicka gra typu roll-and-write dla jednego do ośmiu graczy, oferuje doświadczenie niepodobne do niczego, co wcześniej stworzyło Fantasy Flight Games. Mając do dyspozycji ograniczoną pulę zasobów, musisz ostrożnie zarządzać nawigacją, ekspansją, przemysłem i wojną, gromadząc punkty zwycięstwa i zdobywając prawo do tronu na Mecatol Rex. Czy twoja frakcja zostanie nowymi władcami galaktyki? A może twoje młode imperium popadnie w zapomnienie? W tej strategicznej grze, w którą można grać bez końca, może się zdarzyć wszystko!"})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def LeagueofDungeoneers(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "League of Dungeoneers", 'opis':"League of Dungeoneers (LoD) to szczegółowa gra z gatunku Dungeon Crawl i zarządzania drużyną. Gra została zaprojektowana z myślą o rozgrywce solo/coop, ale może być również rozgrywana z mistrzem gry. Głównym zadaniem gry jest rozwijanie postaci zarówno poprzez zdobywanie doświadczenia, jak i znajdowanie złota, ekwipunku, magicznych i legendarnych przedmiotów, które mogą pomóc w wyprawie. Gra osadzona jest we własnym uniwersum fantasy, zawierającym wiele ras i potworów, których można oczekiwać od klasycznego settingu fantasy. Gracz może rozegrać kampanię dołączoną do gry lub wykonać dowolne z 22 pojedynczych zadań."})
 
    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def AeonTresspassOdyssey(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Aeon Tresspass Odyssey", 'opis':"Aeon Trespass: Odyssey to kampania dla 1-4 graczy o przygodach, eksploracji i zaciekłych bitwach z gigantycznymi potworami. Jest to kooperacyjna gra planszowa z możliwością dokonywania wyborów podczas wielu sesji. Akcja gry Aeon Trespass rozgrywa się w alternatywnej starożytności, gdzie wstrząsający rzeczywistość kataklizm zabił bogów olimpijskich i uwolnił nieziemskich Pierwotnych: Odyssey stawia graczy w roli Argonautów, jedynych ludzi, którzy mogą odeprzeć mrok i naprawić sytuację."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def LegendaryMarvel(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Legendary Marvel", 'opis':"Legendary: A Marvel Deck Building Game osadzona jest w uniwersum Marvel Comics. Aby przygotować grę, gracze wybierają złoczyńcę (Magneto, Loki, Dr. Doom, Red Skull w grze podstawowej), układają pod nim karty ataku tego konkretnego złoczyńcy, a następnie modyfikują talię złoczyńcy w razie potrzeby w oparciu o konkretny schemat tego złoczyńcy. Następnie gracze wybierają kilka talii bohaterów - Spider-Mana, Hulka, Wolverine'a itp. - i tasują je razem; ponieważ gracze używają tylko kilku talii bohaterów z piętnastu dołączonych do gry, talia bohaterów może się znacznie różnić pod względem tego, co jest dostępne."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def Ankh(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Ankh", 'opis':"Wciel się w boga starożytnego Egiptu, rywalizując o przetrwanie, gdy społeczeństwo zaczyna zapominać o dawnych zwyczajach, tak że pozostajesz tylko ty i twoi wyznawcy. Buduj karawany, przyzywaj potwory i nawracaj wyznawców w dążeniu do panowania w Ankh: Gods of Egypt. Bóstwa, potwory i ludzie starożytnego Egiptu zostali z miłością odtworzeni i zinterpretowani na pięknych ilustracjach i szczegółowych miniaturach, a gracze naprawdę poczują się jak bogowie, wstrząsając podstawami Egiptu. Cała rozgrywka w Ankh, w tym walka, jest usprawniona i nielosowa. Rywalizuj i wygrywaj wyłącznie dzięki swojemu boskiemu sprytowi."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def BulletStar(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Bullet Star", 'opis':"Wciel się w rolę najpotężniejszych bohaterek wszechświata, rozwiązując ich spory za pomocą nadmiernej siły ognia! Używaj akcji, aby tworzyć wzory, usuwać pociski z pola widzenia i bombardować przeciwnika! Poradź sobie z kurtyną pocisków nadlatujących na ciebie w każdej rundzie i bądź ostatnią bohaterką stojącą, aby wygrać! Każda bohaterka posiada dynamiczną moc, która zmienia sposób rozgrywki! Kontroluj fajerwerki, zombie, wiadomości i nie tylko!"})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def RailroadInk(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Railroad Ink", 'opis':"W wieloosobowej grze logicznej Railroad Ink celem jest połączenie jak największej liczby wyjść na planszy. W każdej rundzie na środku stołu rzuca się zestawem kości, określając, jakie rodzaje dróg i tras kolejowych są dostępne dla wszystkich graczy. Musisz narysować te trasy na swoich wymazywalnych planszach, aby utworzyć linie transportowe i połączyć swoje wyjścia, starając się zoptymalizować dostępne symbole lepiej niż przeciwnicy. Im więcej wyjść połączysz, tym więcej punktów zdobędziesz na koniec gry, ale tracisz punkty za każdą niekompletną trasę, więc planuj ostrożnie! Wykorzystasz swoje szczęście i spróbujesz rozciągnąć swoją sieć transportową do następnego wyjścia, czy też zagrasz bezpiecznie i rozpoczniesz nową, prostszą w zarządzaniu trasę?"})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def TooManyBones(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Too Many Bones", 'opis':"Too Many Bones to gra RPG z budowaniem kości, która zmienia tradycyjne zasady rzucania kośćmi, wprowadzając zupełnie nowy gatunek. Ta pełna strategii gra fantasy przenosi cię do terytoriów północnych, gdzie grasz jako członek nowej rasy, stawiając czoła rosnącym siłom wroga, a także odpowiedzialnym za to niesławnych 'złolców'. Gra oferuje kampanię Coop lub Solo, przeznaczoną dla 1-4 graczy. W grze znajduje się ponad 100 unikalnych kości umiejętności oraz 4-7 klas do wyboru, co sprawia, że każda bitwa to osobne wyzwanie do rozwiązania. Twoja przygoda składa się z 8-12 bitew, po których dotrzesz do celu i stoczysz walkę z jednym z wielu baronów, aby zdobyć zwycięstwo. Po drodze będziesz musiał podejmować decyzje fabularne, które szybko zmuszą cię do rozważenia ryzyka, nagrody, szans i logiki, z kośćmi wplecionymi w każdy aspekt gry! Twoja drużyna będzie także musiała podjąć inne decyzje: kiedy odpocząć, kiedy eksplorować i jakie walki podjąć. Karty Encounter oferują zabawne zwroty akcji i trochę komicznej ulgi, a wszystko to przygotowuje scenę do kolejnej bitwy."})

    @when_all((m.liczba_graczy == '1') & (m.koszt1 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def HoplomachusVictorum(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Hoplomachus Victorum", 'opis':"Hoplomachus: Victorum to samodzielny tytuł od Chip Theory Games, który rozwija uznany system walki z gier Hoplomachus, dodając nowe zwroty akcji i koncentrując się na bohaterach oraz kampanii. Gra jest przeznaczona do rozgrywki solo, oferując głęboką, satysfakcjonującą przygodę z wieloma decyzjami strategicznymi i ekscytującą walką. Osadzona w epickim i mitycznym świecie Hoplomachus: Victorum, ta edycja łączy mechanizmy walki, które fani znają i kochają, z pięknie zaktualizowaną historią, grafiką oraz projektem."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == '<500') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def OneDeckDungeon(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "One Deck Dungeon", 'opis':"One Deck Dungeon to gra karciana 'roguelike'', w której gracze wyruszają na wyprawę do lochów, gdzie każde podejście jest inne. Gra jest trudna, a postać budujesz od podstaw, korzystając z talii zawierającej różne potwory i inne niebezpieczeństwa, które czyhają w lochach. Każda karta przedstawia przeszkodę do pokonania oraz potencjalne nagrody za jej pokonanie. Po pokonaniu karty, gracze zdobywają doświadczenie, przedmioty lub umiejętności, które umieszczają na swojej karcie postaci, aby śledzić korzyści. Im dłużej eksplorujesz lochy, tym głębiej w nie wchodzisz, a trudność gry szybko rośnie. Jeśli dotrzesz wystarczająco daleko, będziesz musiał zmierzyć się z bossem lochów. Przetrwaj, a staniesz się legendą!  One Deck Dungeon jest przeznaczona dla 1-2 graczy, ale dzięki dodatkowemu zestawowi można grać w większym gronie."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == '<500') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def UnconsiousMind(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Unconsious Mind", 'opis':"Unconscious Mind to gra w stylu euro, w której umieszcza się robotników, buduje silniki, wiele opon i efekty kaskadowe. W swojej turze możesz umieścić jeden lub dwa pomysły (robotników) na centralnym stole spotkań, aby uzyskać dostęp do różnych akcji, takich jak dodawanie kafelków do planszy gracza, dobieranie i zagrywanie kart oraz poruszanie się po Wiedniu. To, gdzie umieścisz swoje Pomysły, decyduje również o tym, jak daleko posunie się kałamarz twojego pierścienia, aktywując rząd lub kolumnę efektów kafelków na twojej planszy gracza. Aby leczyć swoich klientów i interpretować ich sny, musisz pracować z zasobami Wglądu, którymi będziesz zarządzać na wielopoziomowej tarczy. Podczas pracy z jawnymi snami na poziomie powierzchni do głęboko zakorzenionych ukrytych snów, te spostrzeżenia pomogą twoim klientom osiągnąć katharsis. Jest to reprezentowane przez podnoszenie przezroczystych warstw z kart klientów - odblokowując ich bieżące zdolności specjalne i możliwości zdobywania punktów w grze końcowej.Gdy grupa ugruntuje swoją reputację, koniec gry jest sygnalizowany, a członek z największą liczbą punktów wygrywa."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == '<500') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def FlipTown(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Flip Town", 'opis':"Fliptown to gra typu flip-and-write, w której starasz się zdobywać gwiazdki, eksplorując miasteczko na Dzikim Zachodzie. Gra wykorzystuje standardową talię pokerową do prowadzenia rozgrywki w stylu otwartego świata, wraz z tablicami suchościeralnymi, które służą jako mapa każdego gracza.\n W każdej turze należy odwrócić trzy karty, przypisując jedną kartę reprezentującą kolor, jedną kartę reprezentującą wartość i jedną kartę reprezentującą kartę pokera. Kolor karty decyduje o tym, który z czterech regionów zostanie aktywowany, wartość karty decyduje o tym, które miejsce w regionie zostanie zakreślone, a karta pokera wpływa na pięciokartowy układ pokerowy, który jest rozstrzygany na koniec każdej rundy.Każdy z czterech regionów - Trail, Badlands, Mine i Town - oferuje inną łamigłówkę do opanowania, podczas gdy każde miejsce w regionie zapewnia unikalną nagrodę, taką jak gotówka, złoto, pomocne przedmioty, takie jak broń, konie i narzędzia, lub dodatkowe akcje do tworzenia potężnych kombinacji. \nW grze solo można grać, aby osiągnąć wysoki wynik lub rywalizować z jednym z czterech robotów „cowbot”, z których każdy ma własną motywację. \nW rozgrywce wieloosobowej gracze używają „kart wspólnych” w centrum gry, a gracze rozwiązują każdą turę jednocześnie. Dodatkowo, karty nagród dodają konkurencyjne cele, które gracze starają się osiągnąć.\nOprócz standardowej rozgrywki, gracz może wcielić się w jedną z 14 postaci z Dzikiego Zachodu. Każda postać ma unikalny zestaw zasobów początkowych i unikalną zdolność specjalną."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == '<500') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def LegendofHexdom(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Legend of Hexdom", 'opis':"Legend of Hexdom to gra solitaire (ale może być również rozgrywana w trybie kooperacyjnym lub rywalizacyjnym), w której eksplorujesz świat heksów, szukając łupów, zwiększając swoje statystyki, aż będziesz gotowy, by najechać zamki i pokonać bossów.\n Dzięki różnym klasom, każdy bohater posiada swój własny zestaw mocy (i słabości). Możesz znaleźć skarby, klejnoty, relikwie i prezenty, które pomogą Ci w podróży.\n Do gry wystarczy długopis/marker, trzy sześciościenne kości i jedna z map Hexdom. Nasza początkowa kampania obiecuje ponad 250 map w pakiecie startowym, a także mamy nadzieję zbudować społeczność, która będzie się dalej rozwijać."})
    @when_all((m.liczba_graczy == '2') & (m.koszt2 == '<500') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def RoqueDungeon(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Roque Dungeon", 'opis':" Rogue Dungeon to gra typu roguelike, będąca ofertą premium, która oferuje znacznie więcej niż tylko zwykłą talię kart. Do gry dołączona jest mata, która emuluje interfejs użytkownika CRPG, organizując grę w tematyczne sekcje, takie jak broń, tarcze, zbroje, hełmy, rękawice, buty, zwoje i plecak pełen łupów. \nRogue Dungeon jest bardzo grywalne i przepełnione klimatem. Niewiele gier pozwala na przejście od zera do bohatera w ciągu godziny. Gra koncentruje się na zarządzaniu łupami, co nadaje jej szczególny urok. Możesz zacząć grę z kawałkiem mięsa, które używasz do oczarowania wilka, który pomaga ci pokonać zombie. Zombie upuszcza wytrych, którego używasz do otwarcia sejfu, w którym znajduje się klejnotowy kielich. Wymieniasz go na szczęśliwą tarczę, której używasz, by zneutralizować ogień smoka."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == '<500') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def DungeonofDoria(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Dungeon of Doria", 'opis':"Kooperacyjny dungeon crawler dla 1-6 graczy osadzony w świecie fantasy Doria. Jesteście bohaterami, najemnikami i włóczęgami, przybyłymi z odległych zakątków kontynentu Doria w poszukiwaniu przygód, chwały i złota. Ogrom Doria roi się od lochów, wież i piwnic pełnych potworów, skarbów i starożytnych artefaktów. Współpracujcie, aby przetrwać straszliwe niebezpieczeństwa i uciec z lochów Dorii!"})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == 'premium') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def ArkhamHorrorTheCardGame(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Arkham Horror The Card Game", 'opis':"Coś złego dzieje się w Arkham i tylko ty możesz to powstrzymać. Zacierając tradycyjne granice między grami fabularnymi a karcianymi, Arkham Horror: The Card Game to żywa gra karciana pełna lovecraftowskich tajemnic, potworów i szaleństwa!\n W grze ty, sam lub z przyjacielem (lub do trzech przyjaciół z dwoma zestawami podstawowymi), stajesz się śledczym w spokojnym mieście Arkham w Nowej Anglii. Z pewnością masz swoje talenty, ale masz też swoje wady. Być może trochę za bardzo zagłębiłeś się w pisma Necronomiconu, a jego słowa wciąż cię prześladują. Być może czujesz się zmuszony do ukrywania wszelkich oznak zła z innego świata, utrudniając własne śledztwa w celu ochrony cichego zaufania większej populacji. Być może spotkanie z upiornym kultem odciśnie na tobie piętno."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == 'premium') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def CastlesofBurgundy(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Castles of Burgundy", 'opis':"Akcja gry Castles of Burgundy toczy się w regionie Burgundii w późnośredniowiecznej Francji. Każdy gracz wciela się w rolę arystokraty, pierwotnie kontrolującego małe księstwo. Podczas gry starają się budować osady i potężne zamki, prowadzić handel wzdłuż rzeki, eksploatować kopalnie srebra i korzystać z wiedzy podróżników."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == 'premium') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def PuzzleDungeon(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Puzzle Dungeon", 'opis':"Puzzle Dungeon to pasjansowa, modułowa gra planszowa, w której kontrolujesz łowcę potworów przemierzającego lochy wypełnione kilkoma rodzajami potworów i ich królami.\n W grze Puzzle Dungeon gracz używa ograniczonej liczby kart na ręce oraz kart, które rozdaje do gry z talii, aby pokonać wrogów, którzy są rozdawani losowo w każdej grze, tworząc unikalną planszę. Gracze są ograniczeni kolejnością rozdawania kart i kolejnością potworów w lochu, więc do zwycięstwa wymagana jest silna strategia."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == 'premium') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def d6Dungeon(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "2d6 Dungeon", 'opis':"2D6 Dungeon to klasyczna gra typu dungeon crawl. W grze eksplorujesz losowo generowane lochy, walczysz z potworami i zbierasz skarby, zdobywając doświadczenie i poziomy oraz starając się zostać legendarnym poszukiwaczem przygód. Każda przygoda i loch są wyjątkowe."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == 'premium') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def ElderScrollsBetrayaloftheSecondEra(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Elder Scrolls Betrayal of the Second Era", 'opis':"The Elder Scrolls: Betrayal of the Second Era to kooperacyjna przygoda gra planszowa dla 1-4 graczy, której akcja rozgrywa się w Drugiej Erze Tamriel - a konkretnie podczas wydarzeń z Planemeld, gdy Zakon Czarnego Robaka knuje, jak zdobyć Amulet Królów. Podczas gdy mroczny kult knuje, jeden z jego członków planuje jeszcze mroczniejszą zdradę, która na zawsze zwiąże Tamriel z Oblivionem. Poszukiwacze przygód pracują nad odkryciem jej machinacji i powstrzymaniem jej spisku pośród niekończącej się grywalnej zawartości. Podobnie jak w grach The Elder Scrolls, gracze wyruszą w epicką podróż, równoważąc eksplorację, budowanie postaci, nurkowanie w lochach i walkę w zwarciu."})

    @when_all((m.liczba_graczy == '2') & (m.koszt2 == 'premium') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def TownsfolkTussle(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Townsfolk Tussle", 'opis':"Townsfolk Tussle to kooperacyjna gra typu boss battler dla 2-5 graczy. Po śmierci ukochanego szeryfa Eureka Springs, Ruffians przybywają tłumnie, aby wykorzystać bezbronność miasta! To od Ciebie i Twoich współmieszkańców zależy, czy zmiażdżysz tych awanturników do nieprzytomności. A kto wie — jeśli dobrze rozegrasz karty, możesz okazać się godny zostania nowym szeryfem!\n W każdej grze Twoim celem jest pokonanie czterech unikalnych Ruffians, z których każdy jest twardszy od poprzedniego! Będziesz wyposażał swoich mieszkańców w sprzęt, eksplorował Eureka Springs i wymyślał unikalne strategie, aby pokonać jeszcze więcej unikalnych chuliganów."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == '<500') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def ResArcana(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Res Arcana", 'opis':"Res Arcana to gra, w której magowie rywalizują ze sobą o zdobycie potężnych artefaktów i miejsc mocy, wykorzystując esencje takie jak Życie, Śmierć, Elan, Spokój i Złoto, które stanowią podstawę sztuki magii.\n W wysokiej wieży alchemik przygotowuje mikstury, używając fiolek wypełnionych płynami z innego świata. W świętym gaju druid miele zioła do mistycznego rytuału, a w katakumbach Nekromanta przywołuje kościanego smoka.\n Wybierz swojego maga, zbieraj esencje, twórz unikalne artefakty i używaj ich do przywoływania smoków, podbijania miejsc mocy i osiągania zwycięstwa!"})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == '<500') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def Lisboa(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Lisboa", 'opis':"Lisboa to gra planszowa, której akcja toczy się po wielkim trzęsieniu ziemi w 1755 roku, które zniszczyło Lizbonę. Gra polega na odbudowie miasta po katastrofie, a gracze wcielają się w członków szlachty, którzy mają pomóc w jego renowacji, wykorzystując swoje wpływy i zasoby. Gracze współpracują z architektami, by odbudować miasto, z markizem, by rozwijać handel, oraz z królem, by otworzyć wszystkie budynki. Celem nie jest jednak tylko wielkość, sława czy fortuna, ale także peruki – najważniejszy symbol w tamtych czasach."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == '<500') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def Vinhos(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Vinhos", 'opis':"Vinhos to gra, w której wcielasz się w rolę producenta wina w Portugalii. Przez 6 lat będziesz rozwijać swoją działalność, zakładając posiadłości w różnych regionach kraju, kupując winnice i budując winiarnie. Współpracując z doświadczonymi enologami, będziesz zwiększać jakość swojego wina, a najlepsi eksperci pomogą udoskonalić jego cechy na targach „Feira Nacional do Vinho Portugues”, czyli portugalskich targach degustacji wina.\n Sprzedaż wina do lokalnych miejsc w Portugalii pozwoli ci uzyskać fundusze na rozwój firmy i wypłatę pensji dla enologów. Jednak prawdziwa prestiż nie pochodzi tylko z pieniędzy — aby zdobyć międzynarodową reputację, musisz spełniać wymagania różnych krajów, regularnie eksportując wysokiej jakości wino.\n Podczas gry organizowane będą targi degustacji wina. To od ciebie zależy, które wino zaprezentujesz i kiedy, ponieważ wybór najlepszego wina, zarówno pod względem wartości, jak i cech, ma kluczowe znaczenie dla prestiżu twojej firmy."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == '<500') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def DD(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Dungeon and Dragons", 'opis':"Dungeons & Dragons (D&D, w Polsce znane również jako Lochy i Smoki) to prekursorka współczesnych gier fabularnych. Została zaprojektowana przez Gary'ego Gygaxa i Dave'a Arnesona, a po raz pierwszy opublikowana w 1974 roku przez Tactical Studies Rules (TSR). Obecnie grę wydaje Wizards of the Coast, firma należąca do Hasbro.\n D&D wywodzi się z miniaturowych gier figurkowych i stanowiło wariant gry Chainmail, która miała podobny system rozgrywki. Publikacja Dungeons & Dragons jest szeroko uznawana za początek nowoczesnych gier RPG oraz całego przemysłu gier fabularnych. Gra zrewolucjonizowała sposób, w jaki postrzegamy i tworzymy gry, dając początek milionom graczy na całym świecie."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == '<500') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def ClankCatacombs(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Clank Catacombs", 'opis':"Clank! Katakumby to samodzielna przygoda z serii gier budowania talii, która przenosi graczy do tajemniczych i niebezpiecznych katakumb szkieletowego smoka Umbrok Vessna. W tej grze portale prowadzą cię głęboko w lochy, pełne skarbów dla odważnych odkrywców. Więźniowie liczą na to, że ich uwolnisz, a duchy, które raz się obudzą, mogą nawiedzać cię aż do samej śmierci. Pomimo tych niebezpieczeństw, nadszedł czas, by ruszyć w głąb katakumb i stawić czoła wyzwaniom!\n Każda podróż do katakumb jest wyjątkowa, ponieważ to ty układasz płyty, tworząc unikalne lochy. Możesz grać korzystając wyłącznie z nowej talii lochów, ale masz także możliwość dołączenia kart z poprzednich rozszerzeń Clank!. Twoim celem jest zdobycie jak największej fortuny i ucieczka przed smoczym gniewem w tej pełnej emocji grze."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == '<500') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def Vagrantsong(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Vagrantsong", 'opis':"Vagrantsong to kooperacyjna, fabularna gra typu boss battler, w której gracze wcielają się w rolę Vagranta, podróżującego w nadprzyrodzonym pociągu duchów. Twoim celem jest stawienie czoła duchom, zwanymi Haints, które krążą po pociągu. Gra polega na dostosowywaniu swojego stylu gry dzięki umiejętnościom i przedmiotom zdobytym w trakcie podróży, odkrywając sekrety związane z tajemniczym Silver Ferryman.\n Podczas rozgrywki gracze będą musieli współpracować, aby pokonać duchy, odkrywając jednocześnie mroczne sekrety pociągu i jego pasażerów. W grze zawarto głęboką fabułę, pełną wyzwań, intryg i emocjonujących momentów, a przygoda w tym nadprzyrodzonym świecie jest pełna nieoczekiwanych zwrotów akcji."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def DCdeckbuildinggame(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "DC deck building game", 'opis':"DC Comics Deck-Building Game to emocjonująca gra karciana, w której gracze wcielają się w bohaterów Ligi Sprawiedliwości, takich jak Batman, Superman, Wonder Woman, Aquaman, Flash, Zielona Latarnia i Cyborg. Każdy gracz wybiera jednego bohatera, który ma specjalną moc, a następnie rozpoczyna grę z talią dziesięciu kart.\n Celem gry jest zbieranie kart i budowanie swojej talii, by zdobyć coraz większą moc i pokonać zło. Gracze mogą zdobywać karty bohaterów, złoczyńców, superzłoczyńców, ekwipunek, super moce i lokacje. Aby pokonać złoczyńców, gracze muszą posiadać wystarczającą moc, ale po pokonaniu superzłoczyńcy do gry wkracza nowy, który zaatakuje wszystkich bohaterów.\n W trakcie gry musisz mądrze dobierać karty i strategię, aby stworzyć skuteczną talię, która pomoże ci pokonać najsilniejszych przeciwników i zdobyć punkty zwycięstwa. Gra jest dynamiczna i pełna nieoczekiwanych zwrotów akcji, a sukces zależy od sprytu, współpracy z innymi graczami i umiejętności dostosowywania swojej talii w trakcie gry."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def OnMars(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "On Mars", 'opis':"On Mars to zaawansowana gra planszowa, w której gracze wcielają się w rolę astronautów i menedżerów zajmujących się budową i rozwojem kolonii na Marsie. Gra skupia się na eksploracji, zarządzaniu zasobami oraz tworzeniu samowystarczalnej osady na Czerwonej Planecie. Twoim celem jest przejście od początkowej zależności od dostaw z Ziemi do osiągnięcia pełnej niezależności kolonii, zbudowanej na podstawach takich jak woda, energia, powietrze i żywność.\n Na początku, w fazie kolonizacji, będziesz musiał zainwestować w infrastrukturę, budując kluczowe elementy, takie jak kopalnie, generatory energii, szklarnię, fabryki tlenu i schrony. Wraz z rozwojem kolonii, twoje działania będą wymagały coraz bardziej zaawansowanych strategii i zarządzania, w tym regularnych podróży między powierzchnią Marsa a stacją kosmiczną.\nGra oferuje głęboką warstwę strategiczną i wymagającą zarządzanie czasem oraz zasobami. Będziesz musiał zmierzyć się z wyzwaniami związanymi z logistyką, a także podejmować decyzje, które mają wpływ na rozwój kolonii i twoje cele. To prawdziwe wyzwanie, w którym każdy krok wymaga odpowiedniego planowania i przewidywania skutków."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def BrassBirmingham(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Brass Birmingham", 'opis':"Brass: Birmingham to ekonomiczna gra strategiczna będąca kontynuacją arcydzieła Martina Wallace'a z 2007 roku, Brass. Brass: Birmingham opowiada historię konkurujących ze sobą przedsiębiorców w Birmingham podczas rewolucji przemysłowej w latach 1770-1870."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def CallofCthulu(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Call of Cthulu", 'opis':"Call of Cthulhu to gra fabularna z gatunku horror fiction oparta na opowiadaniu H. P. Lovecrafta o tym samym tytule i związanym z nim mitem Cthulhu. Gra, często skracana jako CoC, jest wydawana przez Chaosium; została po raz pierwszy wydana w 1981 roku i jest w siódmej edycji, z licencjonowanymi edycjami obcojęzycznymi. System gry oparty jest na Basic Role-Playing (BRP) firmy Chaosium z dodatkami dla gatunku horroru. Obejmują one specjalne zasady dotyczące zdrowia psychicznego i szczęścia."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def DungeonUniversalis(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Dungeon Universalis", 'opis':"DUN to klasyczna gra planszowa typu Dungeon Crawler dla 1 do 6 graczy (wiek 12+). Gra zawiera wiele trybów rozgrywki, w tym tryb samotnego wilka. System DUN łączy w sobie intuicyjną mechanikę, gry karciane oraz niemal nieograniczone możliwości i opcje RPG.\nDUN oferuje ogromną kampanię narracyjną i kilka niezależnych zadań. Pozwala także na projektowanie własnych zadań lub po prostu korzystanie z podręcznika zasad, systemu i kart do odtwarzania misji i zadań z innych dungeon crawlerów.\nGra dostosowuje się do każdego średniowiecznego tła fantastycznego, ale posiada również własne, unikalne tło: wykorzystane w powieści Raazbal, napisanej przez autora gry i opublikowanej w 2010 roku."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'tak') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def KingdomDeathMonster(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Kingdom Death Monster", 'opis':"Kingdom Death: Monster to w pełni kooperacyjna gra hobbystyczna osadzona w wyjątkowym, koszmarnym świecie pozbawionym większości zasobów naturalnych. W grze kontrolujesz osadę na początku jej istnienia. Gracze walczą z potworami, tworzą broń i sprzęt oraz rozwijają swoją osadę, aby zapewnić sobie przetrwanie z pokolenia na pokolenie. Gra łączy elementy strategii, zarządzania zasobami i intensywnych, emocjonujących walk z potworami w świecie pełnym niebezpieczeństw i mroku."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'deck building'))
    def StarRealms(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Star Realms", 'opis':"Star Realms to kosmiczna gra deckbuildingowa autorstwa Darwina Kastle'a i Roba Dougherty'ego. Jest to szybka gra karciana, w której gracze budują swoje talie, aby walczyć w przestrzeni kosmicznej. Gra łączy elementy budowania talii z interaktywną walką, typową dla gier karcianych. W trakcie rozgrywki gracze wykorzystują Handel, aby pozyskiwać nowe statki i bazy z odkrytych kart w Rzędzie Handlu z Talii Handlu. Zdobyte statki i bazy pozwalają generować więcej Handlu lub Walkę, którą można wykorzystać do atakowania przeciwnika i jego baz. Celem gry jest zredukowanie Autorytetu przeciwnika do zera, co oznacza zwycięstwo."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'strategia') & (m.mechanika_gry_s == 'euro'))
    def TerraMystica(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Terra Mystica", 'opis':"Terra Mystica to gra planszowa, w której gracze wcielają się w rolę jednego z 14 ludów, każdy z nich związany jest z określonym środowiskiem naturalnym. Gra odbywa się w siedmiu różnych krajobrazach, a celem graczy jest terraformowanie tych obszarów w celu dopasowania ich do własnych preferencji środowiskowych i rozwoju. Aby zdobywać punkty, gracze muszą przekształcać sąsiednie tereny, tworzyć osady i rozszerzać swoje wpływy, rywalizując z innymi graczami.\nTo gra strategiczna, w której sukces zależy od precyzyjnego planowania, a nie od przypadku. Każdy lud ma swoje unikalne zdolności, które umożliwiają specyficzne strategie rozwoju. Dodatkowo, istnieją cztery kulty religijne, w które można inwestować, aby zyskać dodatkowe korzyści. Gra nagradza za zdolność zarządzania zasobami, terraformowanie oraz rozwój umiejętności swojej grupy."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'pattern matching'))
    def TickettoRide(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Ticket to Ride", 'opis':"Ticket to Ride to prosta i szybka gra planszowa, której zasady można opanować w mniej niż 15 minut. Gracze zbierają karty różnych typów wagonów kolejowych, które wykorzystują do zdobywania tras kolejowych na mapie Ameryki Północnej. Im dłuższe trasy uda im się zbudować, tym więcej punktów zdobywają. Gracze mogą także zdobywać dodatkowe punkty za realizację Biletów Docelowych, które łączą odległe miasta, oraz za stworzenie najdłuższej ciągłej trasy. Gra łączy prostotę z głęboką strategią, co czyni ją dostępną i angażującą zarówno dla nowych, jak i doświadczonych graczy."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'logiczna') & (m.mechanika_gry_l == 'roll&write'))
    def LettersfromWhitechall(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Letters from Whitechapel", 'opis':"Letters from Whitechapel to gra planszowa osadzona w Londynie z 1888 roku, w czasach morderstw Kuby Rozpruwacza. Gra trwa od 90 do 150 minut, a jej celem jest wciągnięcie graczy w mroczny świat tej słynnej sprawy kryminalnej. Jeden z graczy wciela się w postać Kuby Rozpruwacza, którego zadaniem jest zamordowanie pięciu ofiar, zanim zostanie schwytany przez policję. Pozostali gracze przyjmują rolę detektywów, którzy muszą współpracować, aby złapać mordercę.\n Plansza przedstawia zatłoczone ulice Whitechapel, podzielone na 199 ponumerowanych okręgów połączonych przerywanymi liniami. Kuba Rozpruwacz porusza się tajemniczo między okręgami, starając się nie zostać zauważonym. Policjanci patrolują ulice, próbując przewidzieć, gdzie zabójca może zaatakować, a nędznicy błąkają się po okolicy, mogąc dostarczyć cennych wskazówek. Gra wymaga od graczy współpracy i strategicznego myślenia, aby albo przechytrzyć mordercę, albo ujawnienie tożsamości Kuby Rozpruwacza przed upływem czasu."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'dungeon crawl'))
    def TaintedGrail(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': "Tainted Grail", 'opis':"Tainted Grail: The Fall of Avalon to niezapomniana, solowa lub kooperacyjna przygoda dla 1-4 graczy, łącząca legendy arturiańskie z mitologią celtycką. Gra oferuje unikalną wizję świata, w którym twoje decyzje mają głęboki i znaczący wpływ na wydarzenia. Dzięki rozgałęzionej fabule możesz rozwiązywać problemy na różne sposoby, co sprawia, że każda rozgrywka jest wyjątkowa.\n Gracze stają przed trudnymi decyzjami, a wybory, które podejmą, mogą mieć poważne długoterminowe konsekwencje. W grze spotkasz się z wstrząsającymi wyborem, gdzie pozornie niewielkie zadania mogą prowadzić do wielkich zmian w fabule. To gra pełna emocji, w której każda decyzja liczy się i wpływa na przyszłość Avalon."})

    @when_all((m.liczba_graczy == '3+') & (m.koszt2 == 'premium') & (m.duzy_stol == 'nie') & (m.typ_gry == 'przygodowa') & (m.mechanika_gry_p == 'boss battler'))
    def MarvelChampions(c):
        c.assert_fact({ 'ktora': c.m.ktora, 'gra': 'Marvel Champions', 'opis':'Marvel Champions: The Card Game to kooperacyjna żywa gra karciana dla 1-4 graczy, w której wcielasz się w kultowych bohaterów z uniwersum Marvela, by powstrzymać złoczyńców przed zrealizowaniem ich niecnych planów. Gra pozwala graczom na wspólną walkę z zagrożeniami, takimi jak Rhino, Ultron, czy inne niebezpieczne postacie z komiksów Marvela.\n W trakcie gry wykorzystasz unikalne talie bohaterów, z których każdy ma swoje zdolności i styl gry. Gra jest wspierana przez regularne dodatki, które wprowadzają nowych bohaterów, złoczyńców i scenariusze, co pozwala na ciągłą rozbudowę gry i dostosowanie jej do własnych potrzeb. Współpraca, strategiczne planowanie i wykorzystanie mocy bohaterów to klucz do sukcesu w tej emocjonującej grze karcianej!'})
    @when_all(+m.ktora)
    def output(c):
        print('Gra: {0}.{1} Opis gry: {2}'.format(c.m.ktora, c.m.gra, c.m.opis))


    post('jaka_gra_planszowa',{'ktora': '1', 'liczba_graczy': '3+', 'koszt2': 'premium', 'duzy_stol': 'nie', 'typ_gry': 'przygodowa', 'mechanika_gry_p': 'boss battler'})
